### ISSUE TITLE
Error: Could not resolve TypeScript file without .ts extension

### ISSUE THREAD

**Issue by hbbio** [sveltejs/svelte-preprocess#159]
**Describe the bug**

When using Svelte with an external script, in TypeScript, which itself imports components from other .ts files, we can't omit the `.ts` extension for import.

Otherwise, build fails with:
```
src/main.ts → public/build/bundle.js...
[!] Error: Could not resolve './initials' from src/App.svelte
```

Note that adding the `.ts` extension solves the problem with `svelte-preprocess` but then raises the following TypeScript error:

```
src/main.ts → public/build/bundle.js...
src/App.svelte:1:26 - error TS2691: An import path cannot end with a '.ts' extension. Consider importing './initials' instead.
```

**To Reproduce**

Cf. https://github.com/hbbio/svelte-ts/commit/4ae0dd09b2e8d07f075f7fdcd000ad56f4963225

**Expected behavior**
Ability to import TypeScript files without the ts extension.
**Information about your project:**

- svelte 3.23.0
- typescript 3.9.3
- `svelte-preprocess` 3.7.4
- rollup

**Comment by hbbio** [comment]
The temporary fix to add the `.ts` extension (despite ts error) does not work if the imported file is in a different directory: It tries to resolve the file using the path of the `.svelte` component.

**Comment by kaisermann** [comment]
Fixed in `v4` as we're now only transpiling ts to js. Import resolution should be configured from the bundle side.

**Comment by TobiasMalikowski** [comment]
@kaisermann I'm using svelte-preprocess (4.1.1) and svelte (3.17.3) and face the same issue.

`
// does not work
import { db } from "../firebase/firebase";

// does work, but file extension should not be used
import { db } from "../firebase/firebase.ts";
`

package.json
`
"sapper": "^0.28.0",
"svelte": "^3.17.3",
"svelte-preprocess": "^4.1.1",
`

**Comment by TobiasMalikowski** [comment]
@kaisermann I'm still facing this issue and it's stopping me from using Typescript. If I add the .ts extension in the import everything compiles fine but I get no intellisense. If I remove the .ts extension I get intellisense but compiling stops working.

Can you point me in the right direction?

**Comment by kaisermann** [comment]
@TobiasMalikowski Is your bundler configured to automatically resolve `ts` extensions?

**Comment by TobiasMalikowski** [comment]
@kaisermann Thanks for the quick reply. Yes it is, and in addition I could resolve it just in time :). The issue was caused by **rollup-plugin-typescript2**. I **downgraded** to version **0.21.0** and now the issue is resolved. 

Just in case some else has this issue, this [GitHub Issue](https://github.com/pyoner/svelte-typescript/issues/15) pointed me in the right direction.
